### ISSUE TITLE
no password file created

### ISSUE THREAD

**Issue by ZP-Gaming** [illsk1lls/ZipRipper#10]
i ran the cmd and made sure everything was working properly and it finished and closed the cmd but didnt create any password file like it said it was supposed to. im not sure what is happening, any ideas?

**Comment by illsk1lls** [comment]
are you using redirected onedrive folders?

**Comment by ZP-Gaming** [comment]
dont think so but ill check, pretty sure i deleted one drive off my pc

**Comment by ZP-Gaming** [comment]
yeah one drive isnt even on my pc and the files for the cmd are on my d drive

**Comment by illsk1lls** [comment]
if you type CD %UserProfile%\Desktop into CMD prompt does it take you to your desktop folder?

**Comment by ZP-Gaming** [comment]
says system cannot find path specified
![image_2024-05-12_104529805](https://github.com/illsk1lls/ZipRipper/assets/160547666/6f68f411-54d7-4907-af2d-632029d7994f)

**Comment by illsk1lls** [comment]
what happens if you type
`chcp 1252`
`CD %UserProfile%\Desktop`
does it work then?

**Comment by ZP-Gaming** [comment]
it does not

**Comment by illsk1lls** [comment]
what is your system language?

**Comment by ZP-Gaming** [comment]
English, could it possibly be a antivirus issue because i had to unblock some of the processes to get it to run?
![Capture](https://github.com/illsk1lls/ZipRipper/assets/160547666/608257ef-208d-4300-8463-8aef5128ce70)

**Comment by illsk1lls** [comment]
No it is the language\codepage on your machine..

Your path should look like `C:\Users\Zachary Pugh>`

But instead it looks like `C:ҰUsersҰZachary Pugh>`

**Comment by ZP-Gaming** [comment]
United States

**Comment by illsk1lls** [comment]
Your system is set incorrectly.

Your default codepage should be 437 or 1252, and there should be backslashes ( \ ) in your paths not yen and yuan signs ( Y with 2 slashes, the sign for Japanese money)

**Comment by illsk1lls** [comment]
the answer for your issue is listed here

https://superuser.com/questions/1167662/why-is-windows-10-displaying-as-%C2%A5-on-the-command-line

**Comment by ZP-Gaming** [comment]
never seen that happen before lol, i do have japanese language pack installed but i think it defaulted to that even before it was installed because i remember seeing that symbol in cmd before i even installed the pack

**Comment by illsk1lls** [comment]
Let me know how it goes 👍

**Comment by ZP-Gaming** [comment]
just restarted pc from changing it back to english will run it again and will confirm if it works in a sec

**Comment by illsk1lls** [comment]
I may add a warning for this, i was considering having the script automatically do it, but if it requires a restart maybe a warning with instructions is better

**Comment by illsk1lls** [comment]
type
`ECHO %USERPROFILE%`

**Comment by ZP-Gaming** [comment]
![image_2024-05-12_112602907](https://github.com/illsk1lls/ZipRipper/assets/160547666/48836e40-72c1-4e48-8398-69b330623787)

**Comment by illsk1lls** [comment]
hang tight, your user profile variable is messed up, its missing the path, im finding a fix

**Comment by illsk1lls** [comment]
Open RegEdit on your computer and paste the following address into the top address bar
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList`
On the lefthand side, Ignore S-1-5-XX, starting at the longer keys click each one and on the right side you will see a key called "ProfileImagePath" with a value.  It should have your name in it, but it is also supposed to have the path.  Can you see whats there?

**Comment by ZP-Gaming** [comment]
the value of the profile image path is C:\Users\Zachary Pugh

**Comment by illsk1lls** [comment]
when i echo %userprofile% on my end (and on other machines) i get the full path with my user folder, not my display name...

What you see in your profileimagepath key is what is supposed to be inside that variable.. let me check something else real quick

**Comment by illsk1lls** [comment]
Do you get different output for these two commands?
`echo %userprofile%`
or this
`%systemdrive%\users\%username%`

**Comment by ZP-Gaming** [comment]
basically is just repeating what i typed minus the echo part

**Comment by illsk1lls** [comment]
This 
`echo %systemdrive%\users\%username%`
doesnt display this?
`C:\Users\Zachary Pugh`

**Comment by ZP-Gaming** [comment]
i did that wrong my bad it does display that

**Comment by illsk1lls** [comment]
ok I'm gonna update the script and test it on my end and if it works ill publish it, give me a few minutes to test the changes...

on normal systems they should both display the same thing... but youre not the first person to have issues saving the output file, so maybe this will help multiple issues including the onedrive redirection..

**Comment by ZP-Gaming** [comment]
ok lmk when its updated so i can see if it works on my end

**Comment by illsk1lls** [comment]
All set, download the latest version and give it a shot ;)

**Comment by ZP-Gaming** [comment]
looks like its possibly working now because previously it wasnt even running john the ripper

**Comment by illsk1lls** [comment]
thanks for testing it

**Comment by illsk1lls** [comment]
I will close the issue, please reopen a new one if needed.

*I also added a new wordlist option, if this run doesnt yield results you can update and giv it another shot 😉
