### ISSUE TITLE
How to force it to use brute force

### ISSUE THREAD

**Issue by Tr3yWay996** [illsk1lls/ZipRipper#14]
Ive seen so many extremly complex passwords that it was trying to guees but all this time could have been used to brute force the rather simple password

**Comment by illsk1lls** [comment]
change line #257 from:
`john --wordlist="%ProgramData%\JtR\run\password.lst" --rules=single,all "%ProgramData%\JtR\run\pwhash" !FLAG!`
to
`john --incremental "%ProgramData%\JtR\run\pwhash" !FLAG!`

**Comment by illsk1lls** [comment]
Bruteforce has been added to the main script.

To enter bruteforce mode. Create an empty .TXT file and use it as a custom wordlist by clicking John's mouth on the GUI.  You need to press start after selecting a wordlist option to proceed.
