### ISSUE TITLE
How to run ZipRipper on MacOS

### ISSUE THREAD

**Issue by xbd63** [illsk1lls/ZipRipper#16]
How do I run ZipRipper on MacOS?

Thanks

**Comment by illsk1lls** [comment]
Unfortunately at the current time, ZipRipper is for Windows 8.1/10/11 systems only

JohnTheRipper, however, does work on Macs. [https://www.openwall.com/john/doc/INSTALL.shtml](https://www.openwall.com/john/doc/INSTALL.shtml)
