### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by shaipednekar** [illsk1lls/ZipRipper#17]
I am poor in understanding, but the file I am trying to recover is very important, please help, followed the procedure, but get the below popup.
![image](https://github.com/illsk1lls/ZipRipper/assets/171046530/407e48c2-9d98-48de-9c63-1eef72d1d89d)

**Comment by illsk1lls** [comment]
Its running, in CPU mode, press any key for status

**Comment by illsk1lls** [comment]
I will open discussions for this project later today
