### ISSUE TITLE
drag drop proced

### ISSUE THREAD

**Issue by karubn** [illsk1lls/ZipRipper#19]
a very nice software, thanks geek, ZipRipper my health question pdf rar zip file to your hand.if I drag it onto the cmd, if he chooses the file, he won't automatically ask me about the file again, ZipRipper start quit, don't take out the screen, let ZipRipper start directly.can the cmd script be set this way

**Comment by illsk1lls** [comment]
At the current time, drag and drop/CLI are not supported. I may change the way the script works to allow it sometime soon.

**Comment by karubn** [comment]
Thank you in advance. We are waiting for the drag and drop script as soon as possible. Thank you. Thank you again.
