### ISSUE TITLE
"File is not password protected".

### ISSUE THREAD

**Issue by Bonaf1de** [illsk1lls/ZipRipper#2]
Tried crack a zip-file but getting the message that the file is not password protected?

Perhaps I am understanding the functionality wrong?
I got a zip-file that I can open but the files inside are protected via a password.

**Comment by illsk1lls** [comment]
Navigate to> 
%ProgramData%\JtR\run

then type zip2john C:\FullPathToZip\File.zip and see if it generates a hash, or gives an error message

(luckily the script leaves the temp folders in place when an "unencrypted" file is targeted, for possible debugging)

**Comment by Bonaf1de** [comment]
Thanks for the reaction!

Error:
"Did not find a Central Directory File Header at expected file offset 193582421"

The file was an autoplay executable that I renamed to .zip. I can then open the file (without a prompt for a password) and see the file structure.

**Comment by illsk1lls** [comment]
Unfortunately, zip2john, the tool used to create a hash for zip files, does not currently support sfx exe archives. 

I know renaming the file to zip will allow some compression tools to view the filenames etc, but it does have to be a real zip file for JohnTheRipper to process it.

I believe sfx rar files are supported, but I'm not sure of the extent of support.

**Comment by Bonaf1de** [comment]
Doh, too bad. Thanks for helping me!

**Comment by illsk1lls** [comment]
No problem, I'm going to close the issue since the error wording has been corrected.  As a side note, trying to track this issue down helped improve stability for ZIP and RAR file formats. ;) Totally worth it.

**Comment by illsk1lls** [comment]
No problem, I'm going to close the issue since the error wording has been corrected. As a side note, trying to track this issue down helped improve stability for ZIP and RAR file formats. ;) Totally worth it.
