### ISSUE TITLE
ZipRipper closes without giving a password

### ISSUE THREAD

**Issue by jcrip1526** [illsk1lls/ZipRipper#20]
Hello, I have tried to use Zipripper for the past hour now, but it isn't working. It will let me select my file, then it says to wait a moment. After waiting the program will just close itself and not give me a password. I believe its because at the top it say Open CL Unavailable. How could I fix this?

**Comment by GoldenLufffy** [comment]
I'm having the same issue, I'm on windows 11 via bootcamp with the Radeon Pro 5300m, the file is 2284 kb

**Comment by illsk1lls** [comment]
For Radeon cards, if amdocl64.dll is present at C:\windows\system32\amdocl64.dll, rename the file to amdocl64.dll.old and try to let the script automatically replace it with a newer version... it does not do this itself if you already have/had the file

lmk

**Comment by Schroedingers-Cat** [comment]
Same problem on Win10 with an RX6900XT. The script automatically downloaded OpenCL, the `amdocl64.dll` has a current timestamp. After extracting the files, generating some hashes and a wordlist, the script closes itself.

The 7z file is about 20MB and has no special characters and its name is very short.

Any other idea?

**Comment by illsk1lls** [comment]
You can try renaming amdocl64.dll to amdocl64.dll.old and downloading the latest AMD drivers then try using this script.. (The AMD GPU Driver installer should put the file into driverstore for you then the script below should register it)

https://github.com/ptrumpis/OpenCL-AMD-GPU

AMD support has been experimental, I've been flying blind as I'm an nVidia user.. We have had some success I was under the impression I had it sorted, so lmk for sure

**Comment by IIISuddenIII** [comment]
i have the exact same problem and it doesnt fix by redownloading amdcl64.dll and so on. But the script works with .rar and .zip files, could it probably be a 7z error?

**Comment by illsk1lls** [comment]
It is possible the opencl dll for amd and john are having issues but its more likely you need an exact dll version for your card and the generic(but more compatible than most) one im using might just have an issue, ill look into it further asap

**Comment by IIISuddenIII** [comment]
could you release an update with somekind of a button or so, to start in cpu mode, because my amd isnt working for 7z

**Comment by csPinKie** [comment]
same for me, 7700xt crashing after a few secs

**Comment by illsk1lls** [comment]
The script was updated with a few fixes, I'm not sure if it will help with your specific issues, lmk.

**Comment by illsk1lls** [comment]
Radeon users are now given an option to use CPU mode if the correct OpenCL drivers for their video card is not present.

I will close this issue for now and work on a way to match the driver to the card model using the dll file hashes provided by ATI.  I don't know when this will be completed. Until then AMD users can attempt to download opencl dll files using the link embedded at the bottom of the script to experiment.
