### ISSUE TITLE
Can't pass the "Would you like to split the wordlist?" question 

### ISSUE THREAD

**Issue by Paul-Courbis-de-Bridiers-de-Villemor** [illsk1lls/ZipRipper#29]
Hi

I tried to use ZipRipper but I can't pass teh "Would you like to split the wordlist?" question. I tried to answer OUI (yes) or NON (no) but the question repeats. Peharps is it because I run it on a french Windows ans the retruened answer is neither YES or NO ? (remember years ago I had this issue with the FORMAT command ;-))

Regards

**Comment by illsk1lls** [comment]
Try adding this line to the top of the script

chcp 65001

**Comment by Paul-Courbis-de-Bridiers-de-Villemor** [comment]
This does not change anything

**Comment by illsk1lls** [comment]
Unfortunately I dont have a solution yet.

I am only able to test on english systems as that is my native language

**Comment by Paul-Courbis-de-Bridiers-de-Villemor** [comment]
I'm not sure the problem comes from the language. I removed the question and it works well... Thanks for your work and your support

BTW another stange thing : I have a laptop with a Nvidia GPU RTX 3500 but it is not used by your script. Regards

**Comment by illsk1lls** [comment]
Check and see if the following file is present on your system for GPU support

`C:\Windows\System32\OpenCL.dll'

**Comment by Paul-Courbis-de-Bridiers-de-Villemor** [comment]
Hi

Thanks for your patience. Yes the file is there

Répertoire de C:\Windows\System32

24/07/2024  16:00           478 240 OpenCL.dll
               1 fichier(s)          478 240 octets
               0 Rép(s)  1 702 926 426 112 octets libres

Regards
-- 
Paul Courbis de Bridiers de Villemor

**Comment by illsk1lls** [comment]
Can you type this into cmd prompt and post the results?

`WMIC path Win32_VideoController get Name | findstr "."`

**Comment by Paul-Courbis-de-Bridiers-de-Villemor** [comment]
Here's the result :

C:\Users\paul>WMIC path Win32_VideoController get Name | findstr "."
Name
Intel(R) UHD Graphics
NVIDIA RTX 3500 Ada Generation Laptop GPU

Paul

-- 
Paul Courbis de Bridiers de Villemor

**Comment by illsk1lls** [comment]
Have you tried the latest version of the script?

I implemented a fix a couple days ago that may correct your issue.

**Comment by Paul-Courbis-de-Bridiers-de-Villemor** [comment]
Yes it works great !

Here's the output when starting the new version :

Device 1: NVIDIA RTX 3500 Ada Generation Laptop GPU
Warning: excessive partial hash collisions detected
(cause: the "format" lacks proper binary_hash() function definitions)
Using default input encoding: UTF-8
Loaded 22635 password hashes with 22635 different salts (ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL])
Loaded hashes with cost 1 (HMAC size) varying from 2824 to 85215
Note: Passwords longer than 21 [worst case UTF-8] to 64 [ASCII] rejected

Juste started it, the GPU usage reported by TakManager is still around 0% but the fans are running faster than normal usage. Don't know if its normal

Here's the speed :

0g 0:00:00:47  0g/s 0p/s 5175Kc/s 5175KC/s zorro..123456
0g 0:00:00:54  0g/s 0p/s 5193Kc/s 5193KC/s 123456..kulotz
0g 0:00:05:56  0g/s 0p/s 5240Kc/s 5240KC/s status..123456

**Comment by illsk1lls** [comment]
it should be using the gpu now..

the speeds look ~ correct

**Comment by illsk1lls** [comment]
I did another update to ensure symbols are being used... They SHOULD have been in the version you have. But just in case I added the flag to force the ASCII char set, all 93 uppercase, lowercase, numeric, and symbols, writable chars.

It is still rare to see symbols in the status, but if you are seeing them in your current job you can ignore the new version, as the resume feature may break if you switch during the job.

![Screenshot 2024-09-08 195200](https://github.com/user-attachments/assets/0db78211-0c50-474c-b34e-ac3e894230a9)
