### ISSUE TITLE
GPU MODE shown but only cpu working ?

### ISSUE THREAD

**Issue by Tiguespa** [illsk1lls/ZipRipper#31]
Hello

As title say, my cmd shows GPU Mode but task manager shows only my cpu works at 100% . (GPU remaining at 1-2%)

How can i fix this ?
Thx

**Comment by illsk1lls** [comment]
What kind of GPU do you have and what filetype are you targeting?

**Comment by aihkla** [comment]
Hello, I am using Nvidia 4060TI, i am having the same issue, the CPU is full loading altho the application says its using GPU

**Comment by illsk1lls** [comment]
What kind of file is it?

**Comment by Tiguespa** [comment]
RTX 2060 Super,  .7z file

**Comment by illsk1lls** [comment]
If you make a password protected archive yourself with 7z does it work? with a simple password, like "password"?  ;P

**Comment by illsk1lls** [comment]
Can you screenshot the top of the running window and titlebar? If i can see what john is displaying for the job maybe i can tell whats going on

**Comment by Tiguespa** [comment]
I have it

**Comment by illsk1lls** [comment]
what does the whole titlebar say?

any chance you can screenshot the window?

**Comment by JustinJS** [comment]
![image](https://github.com/user-attachments/assets/0f899eb5-22ad-4e56-a55e-ae45d7a8f7d2)
same issue here with a 4070.

**Comment by JustinJS** [comment]
I figured out my issue, i had started a run in which it was only working on the cpu. when I fixed my drivers, I tried to continue that run. By starting fresh, it fixed my issue.

**Comment by illsk1lls** [comment]
Thank you for posting the fix.

**Comment by someonenameguy** [comment]
@illsk1lls I encounter this same issues but the load on both the CPU and GPU is low.

![Image](https://github.com/user-attachments/assets/e9d71f2e-7644-4b5b-9880-0185d90c89f5)

![Image](https://github.com/user-attachments/assets/127ae067-cbac-40be-ab88-a62171794f78)

**Comment by illsk1lls** [comment]
try disabling your intel GPU in device manager, its a strange bug because john is reporting the correct card

**Comment by someonenameguy** [comment]
@illsk1lls Thanks that worked.

![Image](https://github.com/user-attachments/assets/849a1918-b087-423a-a0c9-d24457e5f2ca)

**Comment by illsk1lls** [comment]
I'll try to see if i can make sure it works correctly automatically without you having to do that. ;)
