### ISSUE TITLE
The app "stuck" unless I spam Enter in the terminal window

### ISSUE THREAD

**Issue by phenomen** [illsk1lls/ZipRipper#40]
Basically, it only continues to work if I press Enter repeatedly, otherwise there's no progress at all, like it's completely idle.

Windows 11, Nvidia.

**Comment by illsk1lls** [comment]
does it say 
"Select" in the top titlebar?

**Comment by phenomen** [comment]
I see. So unless I press a key, it doesn't show the progress. A bit confusing but ok!

**Comment by illsk1lls** [comment]
It should be telling you on the 2nd to last line when you run it.. Is it missing?

![Screenshot 2024-09-12 202850](https://github.com/user-attachments/assets/2b8db52f-e0a1-463d-9c35-1305c8f2b322)
