### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [illsk1lls/ZipRipper#42]
I'm completely unable to use this because it won't even run.  Running it as Administrator immediately fails before doing anything with this error:

'POWERSHELL' is not recognized as an internal or external command, operable program or batch file.
Internet connection not detected...

I do have internet, for one.  No one has put this on the Discussions page, no one on any online forums has ever reported this, and only two open issues - this error appears to be completely undocumented.

As a side note - I know some specifics about the password I'm trying to brute-force, such as length, characters it does have, and characters it doesn't have, can this script use this information to speed up the search?

**Comment by illsk1lls** [comment]
What version of Windows are you running?

**Comment by illsk1lls** [comment]
If anyone else experiences this issue that can reply, please open a new issue, and I will address it.
