### ISSUE TITLE
ZipRipper says file is not password protected even though it is

### ISSUE THREAD

**Issue by Stephen9612** [illsk1lls/ZipRipper#44]
After choosing the file and it runs through the process, it says the zipped file is not password protected.

The file being is processed is a 7z file.

**Comment by bskendig** [comment]
Same problem here. It starts up, then says `"C:\Users\username\Desktop\filename.7z" is not password protected..` and exits.

This issue should be renamed, btw.

**Comment by srt-jay** [comment]
Same. It is the files inside that are password protected, I guess this dev didn't even consider that? Which is odd, most password-protected ZIPs or RAR I see have the files inside password-protected, not the archive itself...
So, what exactly is the purpose of this software again?

**Comment by illsk1lls** [comment]
> Same. It is the files inside that are password protected, I guess this dev didn't even consider that? Which is odd, most password-protected ZIPs or RAR I see have the files inside password-protected, not the archive itself... So, what exactly is the purpose of this software again?

Have you tried creating a password protected archive with a simple password like "password" or "test123" for speedy testing? Perhaps your archive was created with extra security in mind with special methods, or maybe it's not actually a RAR or 7z, some tools merely use the extensions of compatible decompression methods.

It is possible the script is in error but without a baseline archive that will definately work there is no way to know if it is a hashing issue to to the file or the script is having an error..

**Comment by bskendig** [comment]
I wasn't aware that 7Zip archives themselves can be encrypted (or not) and the files within them can also be encrypted (or not).

In my case, I was using an unencrypted archive which contained an AES-128 encrypted file. So I guess ZipRipper was correct in telling me that the 7z file itself isn't password-protected, but I wish it would have tried to extract the encrypted contents.

**Comment by illsk1lls** [comment]
Just to update everyone on this, the problem has been addressed and error reporting has been improved.
