### ISSUE TITLE
Program quits before any cracking can be performed.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [illsk1lls/ZipRipper#55]
Title. I only have a terrible AMD iGPU that has no compute support of any kind, but I have a good processor. The program only runs for a few seconds, then quits with no warning, no error and no nothing. I don't even get a log. My CPU is a Ryzen 5 5600H. My CPU has AVX support (if required). The crash occurs when it tries to generate a hash and the main symptom appears to be the program failing to download dependencies. How do I force CPU only mode, and how do I download and install the dependencies for it?

**Comment by csPinKie** [comment]
same problem here on RX7700XT. simply starts, ramps up fans and closes without any info / output

**Comment by illsk1lls** [comment]
Unfortunately I do not have hardware to test AMD, although there is some success reported. I am working on getting a rig setup to figure out why it is having issues..

**Comment by TheSystemGuy1337** [comment]
> Unfortunately I do not have hardware to test AMD, although there is some success reported. I am working on getting a rig setup to figure out why it is having issues..

If you can't test AMD, a compromise would be to add a disclaimer that it's Nvidia ONLY in the readme. 

ie `This software requires an Nvidia GPU with Compute support. AMD and CPU Only modes are not supported!`

**Comment by illsk1lls** [comment]
Except AMD GPU's and CPU only ARE supported. Like I said there is reported success AFTER work was done alongside users and tested. The only reason it wouldnt work on an AMD system is if you dont have the correct amdocl64.dll installed in system32 to match your card, or if the file is over 1.5gb (which is getting added as the upper filesize limit today)

**Comment by chicagojoe** [comment]
Forgive my ignorance, but shouldn't the remove directory call for JtR and the delete calls for the compressed files be in the online section only? Cause in offline mode it's deleting it too which then causes it to fail trying to load them.

Also, it runs in online mode all the way to :STARTJTR but then just fails after the echo of "Running JohntheRipper..."

When I manually run the command I get this:

> C:\ProgramData\JtR\run>john --wordlist="%ProgramData%\JtR\run\password.lst" --rules=single,all "%ProgramData%\JtR\run\pwhash" --format=7z-opencl
0: Error creating command queue for device 1 (0:0): CL_OUT_OF_HOST_MEMORY (-6), giving up

Dunno if any of this helps, but I tried my best with my limited knowledge.

**Comment by illsk1lls** [comment]
> Forgive my ignorance, but shouldn't the remove directory call for JtR and the delete calls for the compressed files be in the online section only? Cause in offline mode it's deleting it too which then causes it to fail trying to load them.

zr-offline.txt is cab archive that decompresses each resource to the same place the downloads would normally go, after which they are extracted and moved into the JtR folder, I just tested offline mode on my end and it is working.

If you go to `%ProgramData%\JtR\run` in command prompt and type the following command what is the output?
`john --list=opencl-devices`

**Comment by chicagojoe** [comment]
> C:\ProgramData\JtR\run>john --list=opencl-devices
0: Error creating command queue for device 1 (0:0): CL_OUT_OF_HOST_MEMORY (-6), giving up

It also comes back with he same error with --format=zip-opencl as well.

> C:\ProgramData\JtR\run>john --wordlist="%ProgramData%\JtR\run\password.lst" "%ProgramData%\JtR\run\pwhash" --format=ZIP-opencl
0: Error creating command queue for device 1 (0:0): CL_OUT_OF_HOST_MEMORY (-6), giving up

**Comment by illsk1lls** [comment]
can you try renaming amdocl54.dll in system32 to amdocl54.dll.old then run this script:
[](https://github.com/ptrumpis/OpenCL-AMD-GPU)

**Comment by chicagojoe** [comment]
Renamed it to amdocl.dll.old and ran the script. It found them and reloaded them, then when I re-ran ZipRipper it found unmet requirements for opencl again and I let it download again.

Selected the 7z file, it extracted and then just closed again.

Re-ran `john --list=opencl-devices`

it returned: 

> C:\ProgramData\JtR\run>john --list=opencl-devices
0: Error creating command queue for device 1 (0:0): CL_OUT_OF_HOST_MEMORY (-6), giving up

Sorry I can't be of more help.

**Comment by chicagojoe** [comment]
It's 100% an AMD or JohntheRipper issue. Your scripts are working fine. I'm just to ignorant to figure it out though lol. So I guess I'll just keep trying to remember the password for my passwords.7z file.... (I really thought I was being brilliant password protecting that file...)

**Comment by illsk1lls** [comment]
well the password for the file you tested "Desktop.7z" is `family` judging from what you posted 

try using the same command with the opencl flag added
`john --wordlist="%ProgramData%\JtR\run\password.lst" "%ProgramData%\JtR\run\pwhash" --format=7z-opencl`

im guessing that will make it crash though.. it still may be a driver issue.. but i will submit this to the JtR guys and see what they say

**Comment by chicagojoe** [comment]
Yeah, that was just a test file I was using while trying to get it to work on the gpu. Yeah, with the format changed to opencl it crashed.

I also started to wonder if it was due to my file being a split archive, so I ran `copy /b passwords_projectfiles.7z.* passwords_projectfiles.7z` and then ran 7z2john on that file. Still ended up crashing when using any kind of opencl.

I also use Zluda 3.8.1 and am now wondering if that's the issue.

**Comment by illsk1lls** [comment]
@TheSystemGuy1337 the readme has been updated for now, per your request.

**Comment by TheSystemGuy1337** [comment]
> @TheSystemGuy1337 the readme has been updated for now, per your request.

I actually closed this issue because I got a new PC with an Nvidia card and the program works just fine.

**Comment by illsk1lls** [comment]
🤣

You are very motivated my friend! 😉

Very happy it is working for you now and I'll get the AMD guys sorted too.
