### ISSUE TITLE
Add Linux/Bash support

### ISSUE THREAD

**Issue by lolpro11** [illsk1lls/ZipRipper#7]
Is there any way I can run this on linux? I would pefer that I run this on my servers rather than on my laptop.

**Comment by illsk1lls** [comment]
JohnTheRipper was made for linux, there are a few steps/prerequisites and some specific commands you will need to run to get going. ZipRipper specifically, was made to make things easier for Windows users to get started using John..

JohnTheRipper is pretty easy to use, most of the logic in ZipRipper is there to determine filetype, flags to use, etc.. But if you have a specific file you are working on its pretty easy start a job and let it run.. Here are some linux instruction to get you started - https://www.freecodecamp.org/news/crack-passwords-using-john-the-ripper-pentesting-tutorial/
